// Material-UI Custom Components
export { default as CustomButton } from "./CustomButton";
export { default as CustomTextField } from "./CustomTextField";
export { default as CustomCard } from "./CustomCard";
export { default as CustomModal } from "./CustomModal";

// Re-export commonly used Material-UI components
export {
  Box,
  Container,
  Grid,
  Stack,
  Typography,
  Divider,
  Avatar,
  Chip,
  Badge,
  Tooltip,
  IconButton,
  Fab,
  Paper,
  Skeleton,
  Alert,
  Snackbar,
  LinearProgress,
  CircularProgress,
  List,
  ListItem,
  ListItemText,
  ListItemIcon,
  ListItemButton,
  Menu,
  MenuItem,
  MenuList,
  Drawer,
  SwipeableDrawer,
  Tabs,
  Tab,
  Accordion,
  AccordionSummary,
  AccordionDetails,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Checkbox,
  Radio,
  RadioGroup,
  FormControl,
  FormControlLabel,
  FormGroup,
  FormLabel,
  FormHelperText,
  Select,
  Switch,
  Slider,
  Rating,
} from "@mui/material";

// Re-export commonly used Material-UI icons
export {
  Home as HomeIcon,
  Settings as SettingsIcon,
  Person as PersonIcon,
  Search as SearchIcon,
  Add as AddIcon,
  Edit as EditIcon,
  Delete as DeleteIcon,
  Save as SaveIcon,
  Cancel as CancelIcon,
  Check as CheckIcon,
  Close as CloseIcon,
  ArrowBack as ArrowBackIcon,
  ArrowForward as ArrowForwardIcon,
  KeyboardArrowDown as ArrowDownIcon,
  KeyboardArrowUp as ArrowUpIcon,
  MoreVert as MoreVertIcon,
  Menu as MenuIcon,
  AccountCircle as AccountCircleIcon,
  Notifications as NotificationsIcon,
  Mail as MailIcon,
  Phone as PhoneIcon,
  Visibility as VisibilityIcon,
  VisibilityOff as VisibilityOffIcon,
  Download as DownloadIcon,
  Upload as UploadIcon,
  Share as ShareIcon,
  Favorite as FavoriteIcon,
  Star as StarIcon,
  Info as InfoIcon,
  Warning as WarningIcon,
  Error as ErrorIcon,
  CheckCircle as CheckCircleIcon,
} from "@mui/icons-material";
